'use strict';

/** @type {import('@cspell/cspell-types').CSpellUserSettings} */
const config = {
	version: '0.2',
	language: 'en-GB',
	files: ['**/*.{js,mjs,cjs,ts,mts,cts,json,md,yml,css,scss}'],
	ignorePaths: ['**/node_modules', '**/.yarn', '**/coverage', '.wireit', 'dist', 'build'],
	words: [
		'Autofix',
		'browserslist',
		'cooldown',
		'Cooldown',
		'caniuse',
		'color',
		'customignore',
		'Descriptionless',
		'ENOTDIR',
		'esbuild',
		'Hookable',
		'hookable',
		'outdir',
		'libgconf',
		'Linters',
		'linted',
		'Logform',
		'pngquant',
		'pnpm',
		'quuz',
		'rfdc',
		'sass',
		'shinnn',
		'stylehacks',
		'Stylelint',
		'stylelint',
		'stylelintignore',
		'stylelintrc',
		'sugarss',
		'thibaudcolas',
		'uinteger',
		'vars',
		'vscodeignore',
		'wireit',
		'Xerus',
		'Supertypes',
		'Unregistration', // Not a word but is used upstream in the LSP package.
	],
};

module.exports = config;
